version: '3.6'

networks:
  elk:
    driver: bridge

services:

  # Kafka Service Running with Zookeeper
  zookeeper:
    image: 'zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9002
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOSTNAME: localhost
      ALLOW_PLAINTEXT_LISTENER: 1

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

  # Influx DB Server
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: password
# Framework for data visualization
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    
  #Framework for Spark
  spark-master:
    image: bitnami/spark:latest
    ports:
      - '8080:8080'
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark
    user: 1000:100
    ports:
      - 8888:8888
    depends_on:
      - influxdb

    
volumes:
  influxdb:
  grafana:
